name: setup
description: setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v7
      with:
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
        # Required to update npm
        # https://github.com/actions/runner-images/issues/9644
        node-version: 'lts/*'
    - run: yarn
      shell: bash
