language: node_js

node_js:
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run test
# yarn does not support node 4
- nvm install 4
- npm run test

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
