name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: yarn build
      - run: npm install -g npm@latest
      - run: npm pkg delete scripts devDependencies packageManager
      - run: |
          node --version
          npm --version
      - run: npm publish
